### ISSUE TITLE
Fork elasticsearch-js milestones and tasks

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/opensearch-js#1]
We decide to fork [@elastic/elasticsearch-js](https://github.com/elastic/elasticsearch-js) client library which is open source, licensed under Apache License 2.0 to avoid any inconvenience for users due to the new product-checking logic. Due to this product-checking, new versions clients will get reject connections to any open source distribution or fork of Elasticsearch, including:

* All 1.x versions of Open Distro for Elasticsearch (ODFE)
* OpenSearch 1.0

Here are our work plan:

**[M1] Setting up main branch to support existing ODFE v7.10.2** 

- [x] delete all older branches < 7.10 
- [x] delete all the tags and releases
- [x] create 7.x from 7.14
- [x] delete previous main branch and create new main branch from 7.x
- [x] clean main: remove product checker commit
- [x] copy template files related to OpenSearch guidelines
- [x] set up CI to test the package using Elasticsearch OSS Docker image.

**[M2] Clean up existing code and make it ready for OpenSearch development** 

- [x] Remove X-Pack and non oss features/tests
- [x]  Remove ascii docs file
- [x]  Clean example files ?? This might be okay if not done in M2 since it might have some contents related to issues or later PRs. But we should start working on it and do in separate small PRs. Meanwhile should check with @elfisher if we have any doubts.
- [x]  Remove commits not related to >7.10 from main branch (anan)
- [x] Update CI to run with OpenDistro docker image without security plugin

**[M3] Refactor changes and make it work with OpenSearch 1.0.0 clusters** 
- [x] Update licenses (reference PR: [here](https://github.com/opensearch-project/opensearch-go/commit/d2b9e102e5d932f21e6d5c3d7261197d620d8fec) and [here](https://github.com/opensearch-project/opensearch-go/commit/4f86b2b404860945d76cf467601d66dc6250b6c9) ) (anan)
- [x]  Rename (main branch) 
- [x]  CI is expected to pass for OpenSearch and OpenDistro with and with out security
- [x]  create es action and update CI (issue [#72](https://github.com/opensearch-project/opensearch-js/issues/72) ) (probably no need)
- [ ]  doc? 
- [ ]  make the repo public to npm?

**[M4] Get ready for the release and setting up branches for future development** 
- [x] enable codecov test (issue [#70](https://github.com/opensearch-project/opensearch-js/issues/70) )
- [x] finalize readme (issue [ #5](https://github.com/opensearch-project/opensearch-js/issues/5) ) and other docs if needed
- [x] fork main branch to *1.0* branch for release, *1.x* branch for future releases  
- [x] delete all other unwanted branches
- [ ] generate desired artifacts

**Comment by ananzh** [comment]
done all the milestones. close this track task.
