### ISSUE TITLE
Milestone 1 tasks

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-js#73]
In this milestone, we focus on setting up *main* branch that can work with existing 7.10.2 version of ODFE
- [ ] Delete all older branches  < 7.10 
- [ ] Delete all released tags
- [ ] Delete *main* branch(this branch potentially tracks of all 8.x features as well)
- [ ] create *main* branch from 7.x branch
- [ ] Remove product checker commit if present (this is required to make clients work with oss cluster)
- [ ] Copy template files related to OpenSearch guidelines.
- [ ] set up CI and ensure tests pass for Elasticsearch OSS Docker image. This means all the test cases related to oss features from 7.10.2 executes successfully.
