### ISSUE TITLE
Milestone 2 tasks

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-js#74]
In this milestone, we focus on cleaning up existing code and make it ready for OpenSearch development

- [ ] Remove X-Pack and non oss features/tests
- [ ] Remove docs
- [ ] Remove commits not related to >7.10 from *main* branch
- [ ] Update CI to run with  *OpenDistro* docker image with out security plugin
